# Generated by Django 3.2.2 on 2021-05-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q', models.CharField(max_length=128)),
                ('A', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=128)),
                ('region_1', models.CharField(max_length=128)),
                ('region_2', models.CharField(max_length=128)),
                ('region_3', models.CharField(max_length=128)),
                ('region_x', models.IntegerField()),
                ('region_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='xyLocation',
            fields=[
                ('region_code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('region_1', models.CharField(max_length=128)),
                ('region_2', models.CharField(max_length=128, null=True)),
                ('region_3', models.CharField(max_length=128, null=True)),
                ('region_x', models.IntegerField()),
                ('region_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
    ]
