# Generated by Django 3.2.2 on 2021-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthChat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('conversationDate', models.DateField()),
                ('conversationTime', models.DateTimeField()),
                ('qhour', models.CharField(max_length=100)),
                ('day_of_the_week', models.CharField(max_length=100)),
            ],
        ),
    ]
